name: Lighthouse CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Wait for Pages changed to neutral
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-Netlify
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: 'Pages changed - ruby-meetup-calendar'
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'ruby-meetup-calendar'
      - name: Audit URLs using Lighthouse
        if: steps.wait-for-Netlify.outputs.conclusion == 'neutral'
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}
            ${{ steps.netlify.outputs.url }}/groups
          budgetPath: ./.github/budget.json
          uploadArtifacts: true
