name: Monthly Rebuild
on:
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch:

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
