name: Standard

on:
  pull-request:
  push:
jobs:
  standard:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run Standard
      run: standardrb
